[package]
name = "osm_cutter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
project-root = "0.2.2"
xml-rs = "0.8.4"
